name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  buildx:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
#     - name: Login docker hub
#       env:
#         DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
#         DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
#       # 指定login命令登录hub.docker.com，帐号和密码已经在GitHub网页中配置好了
#       run: |
#         echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up Docker Buildx
      # 使用buildx来构建镜像，这个工具功能很丰富
      uses: docker/setup-buildx-action@v2
      id: buildx
      with:
          install: true 
    - name: Build the Docker image
      run:  docker buildx build  --platform=linux/amd64,linux/arm/v7,linux/arm64 . --file Dockerfile --tag humaolin/kafka:2.13-3.2.0
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        file: ./Dockerfile
        tags: humaolin/kafka:2.13-3.2.0
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }} 
# docker build . --file Dockerfile --tag kafka:2.13-2.8.1  --platform=linux/amd64,linux/arm64/v8  \
#         --output "type=image,push=true" \
